# Copyright notice. Lincesed under AGPLV3, AUTHORED BY CLAW COMMAND.

- type: job
  id: BlueshieldMaid
  name: Claw Command Maid
  description: "Act as a servant and comforter for Command and CentCom VIPs."
  playTimeTracker: JobBlueshieldMaid
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      min: 6550 # 1.625 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      min: 13500 # 3.25 hours
    - !type:DepartmentTimeRequirement
      department: Security
      min: 13500 # 3.25 hours
  weight: 20
  startingGear: BlueshieldMaidGear
  icon: "JobIconClawCommandMaid"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Service
  - Janitor
  - Medical
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Bar
  - Kitchen
  - Hydroponics
  - Theatre
  - Cargo
  - Salvage
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldMaidGear
  equipment:
    back: ClothingBackpackBlueshield
    jumpsuit: ClothingUniformJumpskirtJanimaidmini
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesMedSec
    head: ClothingHeadHatCatEarsCosmetic
    gloves: ClothingHandsGlovesColorWhite
    id: BlueshieldPDA
    ears: ClothingHeadsetAltCommand
    #pocket1: UniqueBlueshieldOfficerLockerTeleporter
    outerClothing: ClothingOuterArmorDuraVest
    #belt: ClothingBeltKatanaSheathFilledMaid
  storage:
    back:
    - Zipties
    - Zipties
    - Zipties
    - AdvMopItem
    - MegaSprayBottleSpaceCleaner
    #outerClothing: ClothingBlueshieldArmourVest
    #ears: ClothingHeadsetAltCommand
    #belt: ClothingBeltSecurityFilled
    #pocket1: WeaponPistolMk58
    #pocket2: DeathAcidifierImplanter
